name = "rosalind"
main = "src/index.ts"
compatibility_date = "2023-05-24"
env = { }

route = { pattern = "*.scaus.art/*", zone_name = "scaus.art" }

[triggers]
crons = [ ]

[vars]
ORIGIN_HOSTNAME = "main--rosalind--samircaus.hlx.live"
